src/Domain/Entity/Team.php
<?php
declare(strict_types=1);


namespace Domain\Entity;

use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Domain\Aggregate\Plan;
use Domain\ValueObject\Name;
use Exception;
use InvalidArgumentException;
use Ramsey\Uuid\UuidInterface;
use Symfony\Component\Validator\Constraints\Collection;

class Team
{
    /** @var UuidInterface */
    private $id;

    /** @var Collection|User[] */
    private $users;

    /** @var Name */
    private $name;

    /** @var DateTimeImmutable */
    private $createdAt;

    /** @var Plan */
    private $plan;

    /**
     * Team constructor.
     * @param Name $name
     * @throws Exception
     */
    public function __construct(Name $name)
    {
        $this->users = new ArrayCollection();
        $this->name = $name;
        $this->createdAt = new DateTimeImmutable();
    }

    /**
     * @return UuidInterface
     */
    public function getId(): UuidInterface
    {
        return $this->id;
    }

    /**
     * @return User[]|Collection
     */
    public function getUsers()
    {
        return $this->users;
    }

    /**
     * @return Name
     */
    public function getName(): Name
    {
        return $this->name;
    }

    /**
     * Returns the object a Array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            "id" => $this->id,
            "name" => $this->name,
            "users" => $this->users,
            "createdAt" => $this->createdAt
        ];
    }

    /**
     * @param array $aTeam
     *
     * @throws InvalidArgumentException
     */
    public function patchByArray(array $aTeam): void
    {
        $name = Name::fromString($aTeam['name']);

        $this->name = $name;
    }

    /**
     * @return int
     */
    public function getUserCount(): int
    {
        return count($this->users);
    }
}

src/Application/Controller/TeamController.php
<?php
declare(strict_types=1);

namespace Application\Controller;

use Doctrine\ORM\EntityManagerInterface;
use Domain\Aggregate\Plan;
use Domain\Entity\Team;
use Domain\Entity\User;
use Domain\ValueObject\Name;
use InvalidArgumentException;
use Ramsey\Uuid\Uuid;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Ramsey\Uuid\Exception\InvalidUuidStringException;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Twig\TwigFunction;

/**
 * Class TeamController
 *
 * @property EntityManagerInterface $entityManager
 *
 * @package Application\Controller
 */
final class TeamController extends AbstractController
{

    /**
     * @var EntityManagerInterface
     */
    private $entityManager;

    /**
     * TeamController constructor.
     *
     * @param EntityManagerInterface $entityManager
     */
    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }


    /**
     * @return Response
     */
    public function index(): Response
    {
        $teams = $this->entityManager->getRepository(Team::class)->findAll();


        return $this->render('team/index.html.twig', [
            'teams' => $teams
        ]);
    }


    /**
     * @return Response
     */
    public function add(): Response
    {
        return $this->render('team/add.html.twig');
    }

    /**
     * @param string $team
     *
     * @return Response
     */
    public function edit(string $team): Response
    {
        $team = $this->getTeamByIdString($team);

        return $this->render('team/edit.html.twig', [
            'team' => $team->toArray(),
        ]);
    }

    /**
     * @param string $team
     *
     * @return Response
     */
    public function delete(string $team): Response
    {
        $team = $this->getTeamByIdString($team);

        return $this->render('team/delete.html.twig', [
            'team' => $team->toArray(),
        ]);
    }

    /**
     * @param Request $oRequest
     *
     * @return RedirectResponse
     */
    public function handleAdd(Request $oRequest): RedirectResponse
    {
        $addTeamLog = realpath("") . "/../src/Application/logs/addTeam.log";
        $loggedUser = $this->get('security.token_storage')->getToken()->getUser();
        $request = $oRequest->request->all();

        try {
            $team = new Team(
                Name::fromString($request['name'])
            );
            $this->entityManager->persist($team);
            $this->entityManager->flush();

            $textContent = "Benutzer (" . $loggedUser->getUsername() .
                ") : hat ein neu Team erstellt! -> id: " . $team->getId()->toString() .
                ", Name: " . $team->getName();
            $finalContent = PHP_EOL . date("d-m-Y h:i:sa") . " -> " . $textContent;
            file_put_contents($addTeamLog, $finalContent, FILE_APPEND);

        } catch (InvalidArgumentException $exception) {
            $this->get('session')->getFlashBag()->add('error', $exception->getMessage());
            file_put_contents(
                $addTeamLog,
                PHP_EOL . date("d-m-Y h:i:sa")
                . " -> Benutzer (" . $loggedUser->getUsername() . ") : InvalidArgumentException = " .
                $exception->getMessage(),
                FILE_APPEND
            );
        }

        return $this->redirectToRoute("app_plan_create");
    }

    /**
     * @param Request $oRequest
     * @param string $team
     *
     * @return RedirectResponse
     */
    public function handleEdit(Request $oRequest, string $team): RedirectResponse
    {
        $editTeamLog = realpath("") . "/../src/Application/logs/editTeam.log";
        $loggedUser = $this->get('security.token_storage')->getToken()->getUser();
        $oTeam = $this->getTeamByIdString($team);
        try {
            $oTeam->patchByArray($oRequest->request->all());
        } catch (InvalidArgumentException $exception) {
            file_put_contents(
                $editTeamLog,
                PHP_EOL . date("d-m-Y h:i:sa")
                . " -> Benutzer (" . $loggedUser->getUsername() . ") : InvalidArgumentException = " .
                $exception->getMessage(),
                FILE_APPEND
            );
            throw new BadRequestHttpException($exception->getMessage());
        }
        $this->entityManager->flush();

        $textContent = "Benutzer (" . $loggedUser->getUsername() .
            ") : hat ein Team bearbeitet -> id: " . $oTeam->getId()->toString();
        $finalContent = PHP_EOL . date("d-m-Y h:i:sa") . " -> " . $textContent;
        file_put_contents($editTeamLog, $finalContent, FILE_APPEND);

        return $this->redirectToRoute("app_team");
    }

    /**
     * @param Request $oRequest
     *
     * @return RedirectResponse
     */
    public function handleDelete(Request $oRequest): RedirectResponse
    {
        $deleteTeamLog = realpath("") . "/../src/Application/logs/deleteTeam.log";
        $loggedUser = $this->get('security.token_storage')->getToken()->getUser();
        $team = $oRequest->request->all();
        $teamFinder = $this->entityManager->getRepository(Team::class)->find($team['id']);
        $plansTeamFinder = $this->entityManager->getRepository(Plan::class)->findBy(
            array("team" => $team['id'])
        );

        foreach ($plansTeamFinder as $planTeam){
            $this->entityManager->remove($planTeam);
        }


        $textContent = "Benutzer (" . $loggedUser->getUsername() .
            ") : hat ein Team geloescht -> id: " . $teamFinder->getId()->toString() .
            ", Name: " . $teamFinder->getName();
        $finalContent = PHP_EOL . date("d-m-Y h:i:sa") . " -> " . $textContent;
        file_put_contents($deleteTeamLog, $finalContent, FILE_APPEND);

        $this->entityManager->remove($teamFinder);
        $this->entityManager->flush();


        return $this->redirectToRoute("app_plan_create");
    }

    /**
     * @param string $input
     *
     * @return Team
     */
    private function getTeamByIdString(string $input): Team
    {
        try {
            $id = Uuid::fromString($input);
        } catch (InvalidUuidStringException $exception) {
            throw new NotFoundHttpException("Team doesn't exist");
        }
        $team = $this->entityManager->getRepository(Team::class)->find($id);

        if (!$team instanceof Team) {
            throw new NotFoundHttpException("Team doesn't exist");
        }

        return $team;
    }

    /**
     * @return array
     */
    private function countTeamMembers(): array
    {
        $countMembers = array();
        $findTeamMembers = $this->entityManager->getRepository(User::class)->findAll();
        foreach ($findTeamMembers as $team) {
            var_dump($team);
            $countMembers = [
                'name' => $team->getName(),
                'count' => count($team->getTeam()['name'])
            ];
        }
        return $countMembers;
    }
}

templates/team/add.html.twig
{% extends 'app.html.twig' %}

{% block title %}{{ 'Team erstellen'|trans }}{% endblock %}

{% block content %}
    <!-- User Container -->
    <div class="container userContainer">
        <div class="columns">
            <div class="column col-3 col-mx-auto mainContent">
                <div class="formtitle">
                    <h2 class="h5 tableTitle">
                        <i class="material-icons">
                            settings
                        </i>
                        {{ 'Gruppe erstellen'|trans }}
                    </h2>
                </div>
                <form method="POST" class="form-lg" action="{{ path('app_team_add_submit') }}">
                    <div class="form-data">
                        <div class="form-data-left">
                            <div class="form-group">
                                <label class="form-label" for="name">{{ 'Name'|trans }}</label>
                                <input class="form-input" name="name" type="text" id="name" placeholder="Name" required>
                            </div>

                            <div class="form-data-right">
                                <a href="{{ path('app_team') }}" style="text-decoration: none">
                                    <button type="button" class="button btn">
                                        {{ 'schließen'|trans }}
                                    </button>
                                </a>
                                <button type="submit" class="button btn btn-primary raise">
                                    {{ 'Submit'|trans }}
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block stylesheets %}

{% endblock %}

templates/team/delete.html.twig
{% extends 'app.html.twig' %}

{% block title %}Gruppe löschen{% endblock %}

{% block content %}
    <!-- User Container -->
    <div class="container userContainer">
        <div class="columns">
            <div class="column col-3 col-mx-auto mainContent">
                <div class="formtitle">
                    <h2 class="h5 tableTitle">
                        <i class="material-icons">
                            settings
                        </i>
                        {{ 'Gruppe Löschen'|trans }}
                    </h2>
                </div>
                <form method="POST" class="form-md">
                    <div class="form-data">
                        <div class="form-data-left">
                            <h6>{{ 'Löschung des Gruppes einreichen: '|trans }}</h6>
                            <div class="form-group">
                                <h3><b>{{ team.name }}</b></h3>
                                <input class="form-input" name="id" type="hidden" id="id" placeholder="id"
                                       value="{{ team.id }}">
                            </div>

                            <div class="form-data-right">
                                <a href="{{ path('app_team') }}" style="text-decoration: none">
                                    <button type="button" class="button btn">
                                        {{ 'schließen'|trans }}
                                    </button>
                                </a>
                                <button type="submit" class="button btn btn-primary raise">
                                    {{ 'Submit'|trans }}
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block stylesheets %}

{% endblock %}

templates/team/edit.html.twig
{% extends 'app.html.twig' %}

{% block title %}{{ 'Gruppe bearbeiten'|trans }}{% endblock %}

{% block content %}
    <!-- User Container -->
    <div class="container userContainer">
        <div class="columns">
            <div class="column col-3 col-mx-auto mainContent">
                <div class="formtitle">
                    <h2 class="h5 tableTitle">
                        <i class="material-icons">
                            settings
                        </i>
                        {{ 'Gruppe bearbeiten'|trans }}
                    </h2>
                </div>
                <form method="POST" class="form-lg">
                    <div class="form-data">
                        <div class="form-data-left">
                            <div class="form-group">
                                <label class="form-label" for="name">{{ 'Name'|trans }}</label>
                                <input class="form-input" name="name" type="text" id="name" placeholder="Name"
                                       value="{{ team.name }}" required>
                            </div>

                            <div class="form-data-right">
                                <a href="{{ path('app_team') }}" style="text-decoration: none">
                                    <button type="button" class="button btn">
                                        {{ 'schließen'|trans }}
                                    </button>
                                </a>
                                <button type="submit" class="button btn btn-primary raise">
                                    {{ 'Submit'|trans }}
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block stylesheets %}

{% endblock %}

templates/team/index.html.twig
{% extends 'app.html.twig' %}

{% block title %}{{ 'Gruppen'|trans }}{% endblock %}

{% block content %}
    <div class="container userContainer">
        <div class="columns">
            <div class="col-2 sideContent">
                <!-- Search -->
                <div class="container searchContainer">
                    <h6>{{ 'Gruppensuche'|trans }}</h6>
                    <input type="text" name="Search" id="search" class="single-line-inputs"
                           placeholder="Suchbegriff eingeben"
                           required>
                    <i class="material-icons">
                        search
                    </i>
                </div>
            </div>
            <div class="col-6 mainContent">
                <h2 class="h5 tableTitle">
                    <i class="material-icons">
                        settings
                    </i>
                    <span class="badge" data-badge="{{ teams|length }}">Gruppenliste </span>
                    <a href="{{ path('app_team_add') }}">
                        <button class="button btn btn-primary btn-sm raise">
                            <i class="material-icons">add</i>
                            {{ 'Hinzufügen'|trans }}
                        </button>
                    </a>
                </h2>
                <div class="container">
                    <table class="table table-striped" id="table">
                        <thead>
                        <tr>
                            <th style="width: 6rem"></th>
                            <th>{{ 'Name'|trans }}</th>
                            <th>{{ 'Mitglieder'|trans }}</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for team in teams %}
                            <tr>
                                <td><i class="material-icons">group</i></td>
                                <td>{{ team.name|capitalize }}</td>
                                <td>{{ team.userCount }}</td>
                                <td>
                                    <div class="popover popover-left">
                                        <i class="material-icons">more_vert</i>
                                        <div class="popover-container">
                                            <div class="card">
                                                <div class="card-header">
                                                    <a href="{{ path('app_team_edit',{team: team.id}) }}">
                                                        <button class="button btn btn-primary raise">
                                                            <i class="material-icons">edit</i>
                                                            {{ 'Bearbeiten'|trans }}
                                                        </button>
                                                    </a>
                                                </div>
                                                <div class="card-footer">
                                                    <a href="{{ path('app_team_delete',{team: team.id}) }}">
                                                        <button class="button btn btn-primary raise">
                                                            <i class="material-icons">delete</i>
                                                            {{ 'Löschen'|trans }}
                                                        </button>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}